### ISSUE TITLE
wishlist requests for in-progress work?

### ISSUE THREAD

**Issue by cboettig** [ropensci-archive/wishlist#3]
It's not quite clear where the line is for requests for things that are already happening -- e.g. I know Karthik's working on the rewrite of the rDrop package (okay, that's not really an ropensci package but still looking forward to it) -- should I still list it?  

Relevant to all items but particularly to in-progress stuff, is their a workflow in place to update this list such that finished items get checked off?  e.g. maybe we need a checklist on CRAN submission or something that includes:

> Check that any mentions of your package on the wishlist have been updated

or some such?

**Comment by Ironholds** [comment]
There isn't at the moment, but that sounds like a good approach! I think listing in-progress things is fine; people always need volunteers for tidying around the edges :). Can I suggest writing a "Contributing.md" file and throwing it up in a pull request? Containing "what to do with the ideas", your thoughts around having conversations about ideas, so on and so forth? We can iterate off that.

**Comment by karthik** [comment]
> It's not quite clear where the line is for requests for things that are already happening -- e.g. I know Karthik's working on the rewrite of the rDrop package (okay, that's not really an ropensci package but still looking forward to it) -- should I still list it?

I'm planning to move it to rOpenSci if there aren't objections from anyone. Listing ongoing work from someone here doesn't make much sense to me in the wishlist context. It's really I wish someone wrote a package for x to do y. It can be closed with:
1. Hey we've been looking for a project and have picked this up
2. This already exists or there is ongoing work
3. I can't help but a +1 since I would use it (giving projects like rOpenSci some community buy in to work on it it).

We could create a contributions.md with how to propose (perhaps with a template). What, relevant URLs (including API docs), intended functionality etc. We could do this in issues so that would allow us to close, assign, discuss etc.

The wiki itself can contain a page with lists of projects in a few categories. 
wishlist (up for grabs)
In progress (moved down from wishlist with links to where the project dev is happening)
Completed (with links to CRAN etc).

thoughts?

**Comment by Ironholds** [comment]
Makes sense!

**Comment by cboettig** [comment]
I think Karthik's comments above really nail this, so closing for now.
